version: '3.8'

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: ${HOME}/data//wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: ${HOME}/data/mariadb
                        o: bind
                        type: none
        nginx:
                name: nginx
                driver: local
                driver_opts:
                        device: ${HOME}/data/nginx
                        o: bind
                        type: none          
networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "443:443"
    # depends_on:
    #   - wordpress
    volumes:
      - wordpress:/var/www/
    networks:
      - inception
    restart: always
  # wordpress:
  #   container_name: wordpress
  #   build: ./requirements/wordpress/.
  #   depends_on:
  #     - mariadb
  #   volumes:
  #     - wordpress:/var/www/html
  #   env_file:
  #     - .env
  #   networks:
  #     - inception
  #   restart: always
  mariadb:
    container_name: mariadb
    build: 
      context: .
      dockerfile: mariadb/Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    ports:
        - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    # env_file:
    #   - .env
    networks:
      - inception
    restart: always