version: '3.8'

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: ${HOME}/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: ${HOME}/data/mariadb
                        o: bind
                        type: none     
networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: requirements/nginx/Dockerfile
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/
    networks:
      - inception
    restart: always
  wordpress:
    container_name: wordpress
    build: 
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - WP_TITLE=${WP_TITLE}
        - WP_ADMIN=${WP_ADMIN}
        - WP_ADM_PASS=${WP_ADM_PASS}
        - WP_ADM_EMAIL=${WP_ADM_EMAIL}
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/
    env_file:
      - .env
    networks:
      - inception
    restart: no
  mariadb:
    container_name: mariadb
    build: 
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    ports:
        - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always