version: '3.8'

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: ${HOME}/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: ${HOME}/data/mariadb
                        o: bind
                        type: none     
networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: requirements/nginx/Dockerfile
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/
    networks:
      - inception
    restart: always
  wordpress:
    container_name: wordpress
    build: 
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    environment:
        DOMAIN_NAME: ${DOMAIN_NAME}
        DB_HOST: ${DB_HOST}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        WP_TITLE: ${WP_TITLE}
        WP_ADMIN: ${WP_ADMIN}
        WP_ADM_PASS: ${WP_ADM_PASS}
        WP_ADM_EMAIL: ${WP_ADM_EMAIL}
        WP_USER: ${WP_USER}
        WP_USER_PASS: ${WP_USER_PASS}
        WP_USER_EMAIL: ${WP_USER_EMAIL}
        WP_REDIS_PASSWORD: ${WP_REDIS_PASSWORD}
        WP_CACHE_KEY_SALT: ${WP_CACHE_KEY_SALT}
        FS_USER: ${FS_USER}
    ports:
      - "9000"
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
    container_name: mariadb
    build: 
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    ports:
        - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  vsftpd:
    container_name: vsftpd
    build:
      context: .
      dockerfile: requirements/bonus/vsftpd/Dockerfile
      args:
        - FS_USER=${FS_USER}
        - FS_USER_PASS=${FS_USER_PASS}
    ports:
      - "21:21"
    volumes:
      - wordpress:/var/www
    networks: 
      - inception
    restart: always
  redis:
    container_name: redis
    build:
      context: .
      dockerfile: requirements/bonus/redis/Dockerfile
      args:
        WP_REDIS_PASSWORD: ${WP_REDIS_PASSWORD}
    ports:
      - "6379"
    networks:
      - inception
    restart: always
  adminer:
    container_name: adminer
    build:
      context: .
      dockerfile: requirements/bonus/adminer/Dockerfile
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: always
  chatai:
    container_name: chatai
    build:
      context: .
      dockerfile: requirements/bonus/chatai/Dockerfile
    ports:
      - "8888:8888"
    networks:
      - inception
    restart: always